# 公開するページのURL
baseURL = "https://lab.rd01.net/"

languageCode = "ja"
DefaultContentLanguage = "ja"
HasCJKLanguage = true
enableRobotsTXT = true

# ブログのタイトル
title = "Making Radio Project"

theme = "mainroad"
paginate = 20

# 自己紹介
[Author]
    name = "KIRIAKE Masanori"
    bio = "プログラマみたいなエンジニアみたいな音楽やってるみたいな人"
    avatar = "img/avatar.png"

[Params]
    customCSS = ["css/custom.css"]
    copyright = "Seiken"
    readmore = true
    authorbox = false
    post_meta = ["date", "categories"]
    twitter_cards = true

# ページのテーマカラー
[Params.style.vars]
  highlightColor = "#e22d30"

# SNS等のユーザー名
[Params.widgets.social]
  twitter = "ji6czd"
  github = "ji6czd"

[Params.sidebar]
    home = "right"
    list = "right"
    single = "right"
    widgets = ["search", "recent", "categories", "taglist", "social"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)
